### ISSUE TITLE
Please send the node version with the querysting to the config service

### ISSUE THREAD

**Issue by pigmej** [xeliuqa/PowerScript#2]
You have hardcoded `https://configs.spacemesh.network/config.mainnet.json`

Instead it would be best if you used:  `https://configs.spacemesh.network/config.mainnet.json?node=<node_ver>`

That would point users *always* to the valid config.

ideally you should NOT even need that config because node have the defaults hardcoded in the mainnet config, so you should ONLY override/set what's needed

**Comment by xeliuqa** [comment]
As you said, everything is hardcoded. Powerscript creates a config with GRPC ports only. I let it create a config file in case users want to customize it. Less work modifying script.
And yes i need a config because i run several nodes in same system with different poets

**Comment by xeliuqa** [comment]
Powerscript has been updated.
