### ISSUE TITLE
Smapp post data and switching, nodeid mismatch

### ISSUE THREAD

**Issue by tanvrkhan** [xeliuqa/PowerScript#3]
FATAL   node    preparing POST initializer failed       {"error": "new initializer: `NodeId` config mismatch; expected:something found:something2

Please advise. Sorry if this is not the place for this.

**Comment by xeliuqa** [comment]
This has nothing to do with script. Message is straight forward. You are using wrong node id in whatever config you are doing.

**Comment by tanvrkhan** [comment]
Of course, was an oversight on my part with duplicate node-data folders. thank you
